//English id=1
var TT_language_en = new Array();
TT_language_en["tomtop.message.shoppingCartIsEmpty"]        = 'Shopping cart is empty!';
TT_language_en["tomtop.common.continueShopping"]            = 'Continue Shopping';
TT_language_en["tomtop.message.cannotBeEmpty"]              = 'Can\'t be empty!';
TT_language_en["tomtop.common.tip"]                         = 'Tip';
TT_language_en["tomtop.message.enterYourEmail"]             = 'Please enter your email address.';
TT_language_en["tomtop.message.wrongEmail"]                 = 'You\'ve entered the wrong email format!';
TT_language_en["tomtop.product.ok"]                         = 'Ok';//ok
TT_language_en["tomtop.product.cancel"]                     = 'Cancel';//ok
TT_language_en["tomtop.product.name"]                       = 'Name';//ok
TT_language_en["tomtop.product.mobilePhone"]                = 'Mobile Phone';//ok
TT_language_en["tomtop.product.emailAddress"]               = 'E-mail address';//ok
TT_language_en["tomtop.product.yourTargetPrice"]            = 'Your Target Price';//ok
TT_language_en["tomtop.product.orderQuantity"]              = 'Order Quantity';//ok
TT_language_en["tomtop.product.countryState"]               = 'Country &#47; State';//ok
TT_language_en["tomtop.product.companyName"]                = 'Company Name';//ok
TT_language_en["tomtop.product.writeAnInquiry"]             = 'Write an inquiry';//ok
TT_language_en["tomtop.product.pleaseLetUsKnow"]            = 'Please let us know as much as possible about your inquiry so that we can assist you with your specific needs. We are always happy to help wherever possible.';                        //ok
TT_language_en["tomtop.product.item"]                       = 'Item';//ok
TT_language_en["tomtop.common.itemAddedToCart"]            = 'item added to cart';
TT_language_en["tomtop.common.totalItemInYourCart"]        = 'total item in your cart';
TT_language_en["tomtop.common.viewCart"]                   = 'View Cart';
TT_language_en["tomtop.product.addToCart"]                  = 'Add To Cart';//ok
TT_language_en["tomtop.common.viewMore"]                   = 'View More';
TT_language_en["tomtop.message.enterYourPassword"]    = 'Please enter your password.';
TT_language_en["tomtop.message.usernameOrPassword"]         = 'You\'ve entered an incorrect username or password.';
TT_language_en["tomtop.common.signIn"]                     = 'Sign In';
TT_language_en["tomtop.common.signInWithTomTopAccount"]    = 'Sign in with TOMTOP account';//ok
TT_language_en["tomtop.common.enterYourEmail"]             = 'Enter your email';//ok
TT_language_en["tomtop.common.enterYourPassword"]          = 'Enter your password';//ok
TT_language_en["tomtop.common.forgotPassword"]             = 'Forgot password';//ok
TT_language_en["tomtop.common.signInWithAnExistingAccount"]= 'Sign In with An Existing Account';//ok
TT_language_en["tomtop.common.joinToday"]                  = 'Join today';//ok
TT_language_en["tomtop.common.membersOnlyService"]         = 'Members Only Service';//ok
TT_language_en["tomtop.common.membersOnlyService1"]        = 'Reward Points';//ok
TT_language_en["tomtop.common.membersOnlyService2"]        = 'Exclusive Customer Service';//ok
TT_language_en["tomtop.common.membersOnlyService3"]        = 'Personalized Recommendations';//ok
TT_language_en["tomtop.common.membersOnlyService4"]        = 'Parmanent Shopping Cart';//ok
TT_language_en["tomtop.common.membersOnlyService5"]        = 'Order History';//ok
TT_language_en["tomtop.common.error"]                      = 'Error';
TT_language_en["tomtop.common.successfully"]               = 'Successfully';
TT_language_en["tomtop.common.viewCartCheckOut"]           = 'View Cart & Check out';//ok
TT_language_en["tomtop.common.inStock"]                    = 'In Stock';
TT_language_en["tomtop.common.outStock"]                   = 'Out of Stock';
TT_language_en["tomtop.product.regularPrice"]              = 'Regular Price';
TT_language_en["tomtop.product.saleEndsIn"]                = 'Sale Ends in';

TT_language_en["tomtop.common.chinaWarehouse"]             = 'China Warehouse';
TT_language_en["tomtop.common.ukWarehouse"]                = 'UK Warehouse';
TT_language_en["tomtop.common.italyWarehouse"]             = 'Italy Warehouse';
TT_language_en["tomtop.common.germanyWarehouse"]           = 'Germany Warehouse';
TT_language_en["tomtop.common.usWarehouse"]                = 'US Warehouse';
TT_language_en["tomtop.common.franceWarehouse"]            = 'France Warehouse';
TT_language_en["tomtop.common.spainWarehouse"]             = 'Spain Warehouse';
TT_language_en["tomtop.common.australiaWarehouse"]         = 'Australia Warehouse';
TT_language_en["tomtop.product.shippingFrom"]              = 'Ship From';
TT_language_en["tomtop.product.warehouse"]                 = 'Warehouse';


//Português id=8
var TT_language_pt = new Array();
TT_language_pt["tomtop.message.shoppingCartIsEmpty"]       = 'O carrinho de compra está vazio!';
TT_language_pt["tomtop.common.continueShopping"]           = 'Continue comprado';
TT_language_pt["tomtop.message.cannotBeEmpty"]              = 'Não Pode ser vazio!';
TT_language_pt["tomtop.common.tip"]                        = 'Ponta';
TT_language_pt["tomtop.message.enterYourEmail"]            = 'Por favor, entra o seu endereço de e-mail.';
TT_language_pt["tomtop.message.wrongEmail"]                = 'Você entra a erra forma de endreço de e-mail';
TT_language_pt["tomtop.product.ok"]                        = 'Ok';//ok
TT_language_pt["tomtop.product.cancel"]                    = 'Cancelar';//ok
TT_language_pt["tomtop.product.name"]                      = 'Nome';//ok
TT_language_pt["tomtop.product.mobilePhone"]               = 'Celular';//ok
TT_language_pt["tomtop.product.emailAddress"]              = 'Endereço de e-mail';//ok
TT_language_pt["tomtop.product.yourTargetPrice"]           = 'Seu Destino de Preço';//ok
TT_language_pt["tomtop.product.orderQuantity"]             = 'Quantidade de ordem';//ok
TT_language_pt["tomtop.product.countryState"]              = 'País / Estado';//ok
TT_language_pt["tomtop.product.companyName"]               = 'Nome da Empresa';//ok
TT_language_pt["tomtop.product.writeAnInquiry"]            = 'Escreva um inquérito';//ok
TT_language_pt["tomtop.product.pleaseLetUsKnow"]           = 'Por favor, deixe-nos saber o máximo possível sobre sua pergunta para que possamos ajudá-lo com suas necessidades específicas. Estamos sempre dispostos a ajudar sempre que possível.';//ok
TT_language_pt["tomtop.product.item"]                      = 'Item';//ok
TT_language_pt["tomtop.common.itemAddedToCart"]           = 'Adiciona o item no carrinho de compra';
TT_language_pt["tomtop.common.totalItemInYourCart"]        = 'Todos itens no seu carrinho';
TT_language_pt["tomtop.common.viewCart"]                   = 'Ver Carrinho';
TT_language_pt["tomtop.product.addToCart"]                 = 'Adicionar ao Carinho';//ok
TT_language_pt["tomtop.common.viewMore"]                   = 'Veja mais';
TT_language_pt["tomtop.message.enterYourPassword"]         = 'Por favor, entra a sua senha.';
TT_language_pt["tomtop.message.usernameOrPassword"]         = 'Você entra a senha ou o nome de usário que é erro';
TT_language_pt["tomtop.common.signIn"]                     = 'Assinar em';	//ok
TT_language_pt["tomtop.common.signInWithTomTopAccount"]    = 'Entrar com Conta TOMTOP';//ok
TT_language_pt["tomtop.common.enterYourEmail"]             = 'Digite seu e-mail';//ok
TT_language_pt["tomtop.common.enterYourPassword"]          = 'Coloque sua senha';//ok
TT_language_pt["tomtop.common.forgotPassword"]             = 'Se esquece a senha?';//ok
TT_language_pt["tomtop.common.signInWithAnExistingAccount"]= 'Entrar com uma Conta Existente';//ok
TT_language_pt["tomtop.common.joinToday"]                  = 'Gozar hoje!';//ok
TT_language_pt["tomtop.common.membersOnlyService"]         = 'Serviço para Membros';//ok
TT_language_pt["tomtop.common.membersOnlyService1"]        = '1.Reward Pontos';//ok
TT_language_pt["tomtop.common.membersOnlyService2"]        = '2.Exclusive Atendimento ao Cliente';//ok
TT_language_pt["tomtop.common.membersOnlyService3"]        = '3.Recomendações Personalized';//ok
TT_language_pt["tomtop.common.membersOnlyService4"]        = '4.Permanent Carrinho';//ok
TT_language_pt["tomtop.common.membersOnlyService5"]        = '5.Order História';//ok
TT_language_pt["tomtop.common.error"]                      = 'Erro';
TT_language_pt["tomtop.common.successfully"]               = 'Sucesso';
TT_language_pt["tomtop.common.viewCartCheckOut"]           = 'Ver Carrinho';//ok
TT_language_pt["tomtop.common.inStock"]                    = 'Em estoque';
TT_language_pt["tomtop.common.outStock"]                   = 'Sem Stoque';
TT_language_pt["tomtop.product.regularPrice"]              = 'Preço Normal';
TT_language_pt["tomtop.product.saleEndsIn"]                = 'Venda Termina em';

TT_language_pt["tomtop.common.chinaWarehouse"]             = 'Armazém de China';
TT_language_pt["tomtop.common.ukWarehouse"]                = 'Armazém do Reino Unido';
TT_language_pt["tomtop.common.italyWarehouse"]             = 'Armazém de Itália';
TT_language_pt["tomtop.common.germanyWarehouse"]           = 'Armazém de Alemanha';
TT_language_pt["tomtop.common.usWarehouse"]                = 'Armazém de Estados Unidos';
TT_language_pt["tomtop.common.franceWarehouse"]            = 'Armazém de França';
TT_language_pt["tomtop.common.spainWarehouse"]             = 'Armazém de Espanha';
TT_language_pt["tomtop.common.australiaWarehouse"]         = 'Armazém de Austrália';
TT_language_pt["tomtop.product.shippingFrom"]              = 'Envio de';
TT_language_pt["tomtop.product.warehouse"]                 = 'Armazém';


//Español  id=2
var TT_language_es = new Array();
TT_language_es["tomtop.message.shoppingCartIsEmpty"]        = 'El carrito de compras es vacío.';//ok
TT_language_es["tomtop.common.continueShopping"]            = 'Siga comprando.';//ok
TT_language_es["tomtop.message.cannotBeEmpty"]              = 'No se puede estar vacío!';//ok
TT_language_es["tomtop.common.tip"]                         = 'Consejo';//ok
TT_language_es["tomtop.message.enterYourEmail"]             = 'Por favor ingrese tu dirección de correo electrónico.';//ok
TT_language_es["tomtop.message.wrongEmail"]                 = 'Has entrado en el formato de correo electrónico mal!';//ok
TT_language_es["tomtop.product.ok"]                         = 'Ok';//ok
TT_language_es["tomtop.product.cancel"]                     = 'cancelar';//ok
TT_language_es["tomtop.product.name"]                       = 'nombre';//ok
TT_language_es["tomtop.product.mobilePhone"]                = 'móvil';//ok
TT_language_es["tomtop.product.emailAddress"]               = 'Dirección de correo electrónico';//ok
TT_language_es["tomtop.product.yourTargetPrice"]            = 'Tu precio deseado';//ok
TT_language_es["tomtop.product.orderQuantity"]              = 'cantidad del orden';//ok
TT_language_es["tomtop.product.countryState"]               = 'País &#47 Estado';//ok
TT_language_es["tomtop.product.companyName"]                = 'Nombre de compañía';//ok
TT_language_es["tomtop.product.writeAnInquiry"]             = 'Escribe una investigación';//ok
TT_language_es["tomtop.product.pleaseLetUsKnow"]            = 'Por favor, háganos saber lo más posible acerca de su pregunta para que nosotros le podemos ayudar con sus necesidades específicas. Siempre estamos dispuestos a ayudar que sea posible.';                        //ok
TT_language_es["tomtop.product.item"]                       = 'artículo';//ok
TT_language_es["tomtop.common.itemAddedToCart"]             = 'artículo ha añadido a la carrito';
TT_language_es["tomtop.common.totalItemInYourCart"]         = 'total artículo en su carrito';
TT_language_es["tomtop.common.viewCart"]                    = 'Ver el carrito';
TT_language_es["tomtop.product.addToCart"]                  = 'Añadir al carrito';//ok
TT_language_es["tomtop.common.viewMore"]                    = 'Ver más';
TT_language_es["tomtop.message.enterYourPassword"]          = 'Por favor ingrese tu contraseña';
TT_language_es["tomtop.message.usernameOrPassword"]         = 'Usted ha pasado un nombre de usuario incorrecto o contraseña incorrecta.';
TT_language_es["tomtop.common.signIn"]                     = 'Ingresar';
TT_language_es["tomtop.common.signInWithTomTopAccount"]    = 'Ingresa con la cuenta de TOMTOP';//ok
TT_language_es["tomtop.common.enterYourEmail"]             = 'Entra tu email';//ok
TT_language_es["tomtop.common.enterYourPassword"]          = 'Entra tu contraseña';//ok
TT_language_es["tomtop.common.forgotPassword"]             = '¿Has olvidado tu contraseña?';//ok
TT_language_es["tomtop.common.signInWithAnExistingAccount"]= 'Ingresa con una cuenta existida';//ok
TT_language_es["tomtop.common.joinToday"]                  = '¡Únete hoy!';//ok
TT_language_es["tomtop.common.membersOnlyService"]         = 'Privilegios de Miembros';//ok
TT_language_es["tomtop.common.membersOnlyService1"]        = '1.Puntos de Recompensa';//ok
TT_language_es["tomtop.common.membersOnlyService2"]        = '2.Servicio Exclusivo al Cliente';//ok
TT_language_es["tomtop.common.membersOnlyService3"]        = '3.Recomendaciones Personalizadas';//ok
TT_language_es["tomtop.common.membersOnlyService4"]        = '4.Carrito Permanente';//ok
TT_language_es["tomtop.common.membersOnlyService5"]        = '5.Pedidos de Historia';//ok
TT_language_es["tomtop.common.error"]                      = 'Error';
TT_language_es["tomtop.common.successfully"]               = 'con éxito';
TT_language_es["tomtop.common.viewCartCheckOut"]           = 'Ver el carrito';//ok
TT_language_es["tomtop.common.inStock"]                    = 'Disponible';
TT_language_es["tomtop.common.outStock"]                   = 'Fuera de stock';
TT_language_es["tomtop.product.regularPrice"]              = 'Precio regular';
TT_language_es["tomtop.product.saleEndsIn"]                = 'Termina la venta';

TT_language_es["tomtop.common.chinaWarehouse"]             = 'Almacén de China';
TT_language_es["tomtop.common.ukWarehouse"]                = 'Almacén de Reino Unido';
TT_language_es["tomtop.common.italyWarehouse"]             = 'Almacén de Italia';
TT_language_es["tomtop.common.germanyWarehouse"]           = 'Almacén de Alemania';
TT_language_es["tomtop.common.usWarehouse"]                = 'Almacén de Estados Unidos';
TT_language_es["tomtop.common.franceWarehouse"]            = 'Almacén de Francia';
TT_language_es["tomtop.common.spainWarehouse"]             = 'Almacén de España';
TT_language_es["tomtop.common.australiaWarehouse"]         = 'Almacén de Australia';
TT_language_es["tomtop.product.shippingFrom"]              = 'Enviar desde';
TT_language_es["tomtop.product.warehouse"]                 = 'almacén ';


//Русский  id=3
var TT_language_ru = new Array();
TT_language_ru["tomtop.message.shoppingCartIsEmpty"]                  = 'Ваша корзина пуста';
TT_language_ru["tomtop.common.continueShopping"]           = 'Продолжить покупки';
TT_language_ru["tomtop.message.cannotBeEmpty"]              = 'Не может быть пустым!';
TT_language_ru["tomtop.common.tip"]                        = 'Топ';
TT_language_ru["tomtop.message.enterYourEmail"]          = 'Введите адрес электронной почты';
TT_language_ru["tomtop.message.wrongEmail"]           = 'Вы ввели неверный формат электронной почты!';
TT_language_ru["tomtop.product.ok"]                         = 'Ok';//ok
TT_language_ru["tomtop.product.cancel"]                     = 'Отмена';//ok
TT_language_ru["tomtop.product.name"]                       = 'Имя';//ok
TT_language_ru["tomtop.product.mobilePhone"]                = 'Мобильный телефон';//ok
TT_language_ru["tomtop.product.emailAddress"]               = 'Адрес электронной почты';//ok
TT_language_ru["tomtop.product.yourTargetPrice"]            = 'Ваша Целевая цена';//ok
TT_language_ru["tomtop.product.orderQuantity"]              = 'Заказанное Количество';//ok
TT_language_ru["tomtop.product.countryState"]               = 'Штат';//ok
TT_language_ru["tomtop.product.companyName"]                = 'Название компании';//ok
TT_language_ru["tomtop.product.writeAnInquiry"]             = 'Напишите запрос';//ok
TT_language_ru["tomtop.product.pleaseLetUsKnow"]            = 'Пожалуйста, сообщите как можно больше информации о Вашем вопросе, так что бы мы могли помочь вам с вашими конкретными потребностями. Мы всегда рады помочь, как можем.';                        //ok
TT_language_ru["tomtop.product.item"]                       = 'Товар';//ok
TT_language_ru["tomtop.common.itemAddedToCart"]            = 'Пункт добавлен в корзину';
TT_language_ru["tomtop.common.totalItemInYourCart"]        = 'Все товары в Вашей корзине';
TT_language_ru["tomtop.common.viewCart"]                   = 'Корзина';
TT_language_ru["tomtop.product.addToCart"]                  = 'Добавить в корзину';//ok
TT_language_ru["tomtop.common.viewMore"]                   = 'Просмотреть больше';
TT_language_ru["tomtop.message.enterYourPassword"]    = 'Пожалуйста введите ваш пароль.';
TT_language_ru["tomtop.message.usernameOrPassword"]         = 'Вы ввели неправильный логин или пароль.';
TT_language_ru["tomtop.common.signIn"]                     = 'Войти в систему';
TT_language_ru["tomtop.common.signInWithTomTopAccount"]    = 'Войти в аккаунт TOMTOP';//ok
TT_language_ru["tomtop.common.enterYourEmail"]             = 'Введите адрес электронной почты';//ok
TT_language_ru["tomtop.common.enterYourPassword"]          = 'Введите ваш пароль';//ok
TT_language_ru["tomtop.common.forgotPassword"]             = 'Забыли пароль?';//ok
TT_language_ru["tomtop.common.signInWithAnExistingAccount"]= 'Вход в существующий аккаунт';//ok
TT_language_ru["tomtop.common.joinToday"]                  = 'Присоединяйся сегодня!';//ok
TT_language_ru["tomtop.common.membersOnlyService"]         = 'Услуга только для пользователей';//ok
TT_language_ru["tomtop.common.membersOnlyService1"]        = '1.Полученные очки';//ok
TT_language_ru["tomtop.common.membersOnlyService2"]        = '2.Ексклюзивное Обслуживание клиентов';//ok
TT_language_ru["tomtop.common.membersOnlyService3"]        = '3.Личные Рекомендации';//ok
TT_language_ru["tomtop.common.membersOnlyService4"]        = '4.Постоянная Корзина';//ok
TT_language_ru["tomtop.common.membersOnlyService5"]        = '5.История заказов';//ok
TT_language_ru["tomtop.common.error"]                      = 'ошибка';
TT_language_ru["tomtop.common.successfully"]               = 'Успешно';
TT_language_ru["tomtop.common.viewCartCheckOut"]           = 'Корзина';//ok
TT_language_ru["tomtop.common.inStock"]                    = 'В наличии';
TT_language_ru["tomtop.common.outStock"]                   = 'Нет на складе';
TT_language_ru["tomtop.product.regularPrice"]              = 'Обычная цена';
TT_language_ru["tomtop.product.saleEndsIn"]                = 'Окончание продаж в';

TT_language_ru["tomtop.common.chinaWarehouse"]             = 'Китай склад';
TT_language_ru["tomtop.common.ukWarehouse"]                = 'Соединенное Королевство склад';
TT_language_ru["tomtop.common.italyWarehouse"]             = 'Склад в Италии';
TT_language_ru["tomtop.common.germanyWarehouse"]           = 'Склад в Германии';
TT_language_ru["tomtop.common.usWarehouse"]                = 'Склад США';
TT_language_ru["tomtop.common.franceWarehouse"]            = 'Франция склад';
TT_language_ru["tomtop.common.spainWarehouse"]             = 'Испания склад';
TT_language_ru["tomtop.common.australiaWarehouse"]         = 'Австралия склад';
TT_language_ru["tomtop.product.shippingFrom"]              = 'Доставка из';
TT_language_ru["tomtop.product.warehouse"]                 = 'Склад ';


//Deutsch  id=4
var TT_language_de = new Array();
TT_language_de["tomtop.message.shoppingCartIsEmpty"]        = 'Der Warenkorb ist leer!';
TT_language_de["tomtop.common.continueShopping"]            = 'Mit dem Einkaufen fortfahren';
TT_language_de["tomtop.message.cannotBeEmpty"]              = 'Darf nicht leer sein!';
TT_language_de["tomtop.common.tip"]                         = 'Spitze';
TT_language_de["tomtop.message.enterYourEmail"]             = 'Geben Sie bitte Ihre Email-Adresse ein.';
TT_language_de["tomtop.message.wrongEmail"]                 = 'Sie haben die falsche E-Mail-Format eingegeben!';
TT_language_de["tomtop.product.ok"]                         = 'Ok';//ok
TT_language_de["tomtop.product.cancel"]                     = 'Absagen';//ok
TT_language_de["tomtop.product.name"]                       = 'Name';//ok
TT_language_de["tomtop.product.mobilePhone"]                = 'Handy';//ok
TT_language_de["tomtop.product.emailAddress"]               = 'E-Mail-Addresse';//ok
TT_language_de["tomtop.product.yourTargetPrice"]            = 'Ihr Zielpreis';//ok
TT_language_de["tomtop.product.orderQuantity"]              = 'Bestellmenge';//ok
TT_language_de["tomtop.product.countryState"]               = 'Land &#47; Region';//ok
TT_language_de["tomtop.product.companyName"]                = 'Name der Firma';//ok
TT_language_de["tomtop.product.writeAnInquiry"]             = 'Schreiben Sie eine Anfrage';//ok
TT_language_de["tomtop.product.pleaseLetUsKnow"]            = 'Bitte lassen Sie uns Ihre Anfrage baldmöglichst wissen , damit wir Ihnen mit Ihren spezifischen Bedürfnissen zu unterstützen. Wir sind immer glücklich zu helfen, wo immer möglich.';                        //ok
TT_language_de["tomtop.product.item"]                       = 'Artikel';//ok
TT_language_de["tomtop.common.itemAddedToCart"]            = 'Artikel wurde dem Warenkorb hinzugefügt';
TT_language_de["tomtop.common.totalItemInYourCart"]        = 'Gesamt Artikel in den Warenkorb';
TT_language_de["tomtop.common.viewCart"]                   = 'Zum Warenkorb';
TT_language_de["tomtop.product.addToCart"]                  = 'In den Warenkorb legen';//ok
TT_language_de["tomtop.common.viewMore"]                   = 'Mehr anzeigen';
TT_language_de["tomtop.message.enterYourPassword"]         = 'Bitte geben Sie Ihr Passwort ein.';
TT_language_de["tomtop.message.usernameOrPassword"]         = 'Sie haben einen falschen Benutzername oder Passwort eingegeben.';
TT_language_de["tomtop.common.signIn"]                     = '"Anmelden';
TT_language_de["tomtop.common.signInWithTomTopAccount"]    = 'Anmeldung mit TOMTOP Konto';//ok
TT_language_de["tomtop.common.enterYourEmail"]             = 'Geben Sie Ihre Email-Adresse ein';//ok
TT_language_de["tomtop.common.enterYourPassword"]          = 'Geben Sie Ihr Passwort';//ok
TT_language_de["tomtop.common.forgotPassword"]             = 'Passwort vergessen?';//ok
TT_language_de["tomtop.common.signInWithAnExistingAccount"]= 'Einloggen mit einem bestehenden Konto';//ok
TT_language_de["tomtop.common.joinToday"]                  = 'Tritt heute bei!';//ok
TT_language_de["tomtop.common.membersOnlyService"]         = 'Nur für Mitglieder des Service';//ok
TT_language_de["tomtop.common.membersOnlyService1"]        = '1.Reward Punkte';//ok
TT_language_de["tomtop.common.membersOnlyService2"]        = '2.Exclusive Kundenservice';//ok
TT_language_de["tomtop.common.membersOnlyService3"]        = '3.Personalized Empfehlungen';//ok
TT_language_de["tomtop.common.membersOnlyService4"]        = '4.kprmanent Einkaufswagen';//ok
TT_language_de["tomtop.common.membersOnlyService5"]        = '5.Order Geschichte';//ok
TT_language_de["tomtop.common.error"]                      = 'Fehler';
TT_language_de["tomtop.common.successfully"]               = 'Erfolgreich';
TT_language_de["tomtop.common.viewCartCheckOut"]           = 'Zum Warenkorb';//ok
TT_language_de["tomtop.common.inStock"]                    = 'Auf Lager';
TT_language_de["tomtop.common.outStock"]                   = 'Ausverkauft';
TT_language_de["tomtop.product.regularPrice"]              = 'Normalpreis';
TT_language_de["tomtop.product.saleEndsIn"]                = 'Verkauf endet in';

TT_language_de["tomtop.common.chinaWarehouse"]             = 'China-Lager';
TT_language_de["tomtop.common.ukWarehouse"]                = 'Großbritannien-Lager';
TT_language_de["tomtop.common.italyWarehouse"]             = 'Italien-Lager';
TT_language_de["tomtop.common.germanyWarehouse"]           = 'Deutschland-Lager';
TT_language_de["tomtop.common.usWarehouse"]                = 'USA-Lager';
TT_language_de["tomtop.common.franceWarehouse"]            = 'Frankreich-Lager';
TT_language_de["tomtop.common.spainWarehouse"]             = 'Spanien-Lager';
TT_language_de["tomtop.common.australiaWarehouse"]         = 'Australien-Lager';
TT_language_de["tomtop.product.shippingFrom"]              = 'Versand von';
TT_language_de["tomtop.product.warehouse"]                 = 'Lager ';


//Français id=5
var TT_language_fr = new Array();
TT_language_fr["tomtop.message.shoppingCartIsEmpty"]        = 'Le panier d\'achat est vide!';
TT_language_fr["tomtop.common.continueShopping"]            = 'Continuer mes achats';
TT_language_fr["tomtop.message.cannotBeEmpty"]              = 'Vous ne pouvez pas être vide!';
TT_language_fr["tomtop.common.tip"]                         = 'Pointe';
TT_language_fr["tomtop.message.enterYourEmail"]             = 'Entrez votre adresse e-mail,s\'il vous plaît!';
TT_language_fr["tomtop.message.wrongEmail"]                 = 'Vous avez entré le format e-mail erronée!';
TT_language_fr["tomtop.product.ok"]                         = 'D\'accord';//ok
TT_language_fr["tomtop.product.cancel"]                     = 'Annuler';//ok
TT_language_fr["tomtop.product.name"]                       = 'prénom';//ok
TT_language_fr["tomtop.product.mobilePhone"]                = 'Portable';//ok
TT_language_fr["tomtop.product.emailAddress"]               = 'Adresse d\'e-mail';//ok
TT_language_fr["tomtop.product.yourTargetPrice"]            = 'Votre prix cible';//ok
TT_language_fr["tomtop.product.orderQuantity"]              = 'Quantité de Commande';//ok
TT_language_fr["tomtop.product.countryState"]               = 'Etat';//ok
TT_language_fr["tomtop.product.companyName"]                = 'Nom de la compagnie';//ok
TT_language_fr["tomtop.product.writeAnInquiry"]             = 'Écrivez une enquête';//ok
TT_language_fr["tomtop.product.pleaseLetUsKnow"]            = 'laissez-nous savoir autant que possible sur votre demande afin que nous puissions vous aider avec vos besoins spécifiques,S\'il vous plaît . Nous sommes toujours heureux d\'aider autant que possible.';                        //ok
TT_language_fr["tomtop.product.item"]                       = 'Article';//ok
TT_language_fr["tomtop.common.itemAddedToCart"]            = 'article ajouté au panier';
TT_language_fr["tomtop.common.totalItemInYourCart"]        = 'article totale dans votre panier';
TT_language_fr["tomtop.common.viewCart"]                   = 'Voir le panier';
TT_language_fr["tomtop.product.addToCart"]                  = 'Ajouter au panier';//ok
TT_language_fr["tomtop.common.viewMore"]                   = 'Voir plus';
TT_language_fr["tomtop.message.enterYourPassword"]        = 'Tapez votre mot de passe';
TT_language_fr["tomtop.message.usernameOrPassword"]         = 'Vous avez entré un incorrect nom d\'utilisateur ou incorrecte mot de passe.';
TT_language_fr["tomtop.common.signIn"]                     = 'Se connecter';
TT_language_fr["tomtop.common.signInWithTomTopAccount"]    = 'Connectez-vous avec compte TOMTOP';//ok
TT_language_fr["tomtop.common.enterYourEmail"]             = 'Entrer votre Email';//ok
TT_language_fr["tomtop.common.enterYourPassword"]          = 'Tapez votre mot de passe';//ok
TT_language_fr["tomtop.common.forgotPassword"]             = 'mot de passe oublié?';//ok
TT_language_fr["tomtop.common.signInWithAnExistingAccount"]= 'Connectez-vous avec un compte existant';//ok
TT_language_fr["tomtop.common.joinToday"]                  = 'Joignez aujourd\'hui!';//ok
TT_language_fr["tomtop.common.membersOnlyService"]         = 'Seuls les membres de services';//ok
TT_language_fr["tomtop.common.membersOnlyService1"]        = '1.Points de récompense';//ok
TT_language_fr["tomtop.common.membersOnlyService2"]        = '2.Service à la clientèle exclusif';//ok
TT_language_fr["tomtop.common.membersOnlyService3"]        = '3.recommandations personnalisées';//ok
TT_language_fr["tomtop.common.membersOnlyService4"]        = '4.Permanent Panier';//ok
TT_language_fr["tomtop.common.membersOnlyService5"]        = '5.Historique des commandes';//ok
TT_language_fr["tomtop.common.error"]                      = 'Erreur';
TT_language_fr["tomtop.common.successfully"]               = 'Succès';
TT_language_fr["tomtop.common.viewCartCheckOut"]           = 'Voir le panier';//ok
TT_language_fr["tomtop.common.inStock"]                    = 'En stock';
TT_language_fr["tomtop.common.outStock"]                   = 'Rupture de stock';
TT_language_fr["tomtop.product.regularPrice"]              = 'Prix habituel';
TT_language_fr["tomtop.product.saleEndsIn"]                = 'Vente se termine dans';

TT_language_fr["tomtop.common.chinaWarehouse"]             = 'Entrepôt de Chine';
TT_language_fr["tomtop.common.ukWarehouse"]                = 'Entrepôt de Royaume-Uni';
TT_language_fr["tomtop.common.italyWarehouse"]             = 'Entrepôt d\'Italie';
TT_language_fr["tomtop.common.germanyWarehouse"]           = 'Entrepôt d\'Allemagne';
TT_language_fr["tomtop.common.usWarehouse"]                = 'Entrepôt des États-Unis';
TT_language_fr["tomtop.common.franceWarehouse"]            = 'Entrepôt de France';
TT_language_fr["tomtop.common.spainWarehouse"]             = 'Entrepôt d\'Espagne';
TT_language_fr["tomtop.common.australiaWarehouse"]         = 'Entrepôt d\'Australie';
TT_language_fr["tomtop.product.shippingFrom"]              = 'De expédition';
TT_language_fr["tomtop.product.warehouse"]                 = 'Entrepôt';



//Italiano id = 6
var TT_language_it = new Array();
TT_language_it["tomtop.message.shoppingCartIsEmpty"]       = 'Il carrello è vuoto!';
TT_language_it["tomtop.common.continueShopping"]           = 'Continua a fare acquisti';
TT_language_it["tomtop.message.cannotBeEmpty"]              = 'Non può essere vuoto!';
TT_language_it["tomtop.common.tip"]                        = 'Suggerimento';
TT_language_it["tomtop.message.enterYourEmail"]          = 'Inserisci il tuo indirizzo email.';
TT_language_it["tomtop.message.wrongEmail"]                = 'Il formato e-mail  non corretto!';
TT_language_it["tomtop.product.ok"]                        = 'Ok';//ok
TT_language_it["tomtop.product.cancel"]                    = 'Cancella';//ok
TT_language_it["tomtop.product.name"]                      = 'Nome';//ok
TT_language_it["tomtop.product.mobilePhone"]               = 'Cellulare';//ok
TT_language_it["tomtop.product.emailAddress"]              = 'Indirizzo email';//ok
TT_language_it["tomtop.product.yourTargetPrice"]           = 'Il tuo Prezzo Obiettivo';//ok
TT_language_it["tomtop.product.orderQuantity"]             = 'Quantità d\'Ordine';//ok
TT_language_it["tomtop.product.countryState"]              = 'Paese / Stato';//ok
TT_language_it["tomtop.product.companyName"]               = 'Nome della ditta';//ok
TT_language_it["tomtop.product.writeAnInquiry"]            = 'ScrivI una richiesta';//ok
TT_language_it["tomtop.product.pleaseLetUsKnow"]           = 'Fateci sapere il più possibile su vostra richiesta in modo che possiamo aiutarvi con le vostre esigenze specifiche. Siamo sempre felici di aiutare per quanto possibile.';//ok
TT_language_it["tomtop.product.item"]                      = 'Articolo';//ok
TT_language_it["tomtop.common.itemAddedToCart"]           = 'Prodotto aggiunto al carrello';
TT_language_it["tomtop.common.totalItemInYourCart"]        = 'Articolo totale nel carrello';
TT_language_it["tomtop.common.viewCart"]                   = 'Vedi il Carrello';
TT_language_it["tomtop.product.addToCart"]                 = 'Aggiungi al Carrello';//ok
TT_language_it["tomtop.common.viewMore"]                   = 'Visualizza altro';
TT_language_it["tomtop.message.enterYourPassword"]    = 'Inserisci la tua password.';
TT_language_it["tomtop.message.usernameOrPassword"]         = 'Il nome utente o password non corretta.';
TT_language_it["tomtop.common.signIn"]                     = 'Registrati';
TT_language_it["tomtop.common.signInWithTomTopAccount"]    = 'Accedi con conto TOMTOP';//ok
TT_language_it["tomtop.common.enterYourEmail"]             = 'Inserisci il tuo indirizzo email';//ok
TT_language_it["tomtop.common.enterYourPassword"]          = 'Inserisci la tua codice d\'ordine';//ok
TT_language_it["tomtop.common.forgotPassword"]             = 'Ha dimenticato la codice d\'ordine?';//ok
TT_language_it["tomtop.common.signInWithAnExistingAccount"]= 'Accedi con un conto esistente';//ok
TT_language_it["tomtop.common.joinToday"]                  = 'Unisciti oggi!';//ok
TT_language_it["tomtop.common.membersOnlyService"]         = 'Servizi esclusivi ai membri';//ok
TT_language_it["tomtop.common.membersOnlyService1"]        = '1.Punti di Ricompensa';//ok
TT_language_it["tomtop.common.membersOnlyService2"]        = '2.Exclusive Servizio Clienti';//ok
TT_language_it["tomtop.common.membersOnlyService3"]        = '3.Raccomandazioni personalizzato';//ok
TT_language_it["tomtop.common.membersOnlyService4"]        = '4.Carrello Permanente';//ok
TT_language_it["tomtop.common.membersOnlyService5"]        = '5.Storia d\'Ordine';//ok
TT_language_it["tomtop.common.error"]                      = 'Errore';
TT_language_it["tomtop.common.successfully"]               = 'Con successo';
TT_language_it["tomtop.common.viewCartCheckOut"]           = 'Vedi il Carrello';//ok
TT_language_it["tomtop.common.inStock"]                    = 'Disponibile';
TT_language_it["tomtop.common.outStock"]                   = 'Esaurito';
TT_language_it["tomtop.product.regularPrice"]              = 'Prezzo regolare';
TT_language_it["tomtop.product.saleEndsIn"]                = 'Vendita scaduta';

TT_language_it["tomtop.common.chinaWarehouse"]             = 'Magazzino della Cina';
TT_language_it["tomtop.common.ukWarehouse"]                = 'Regno Unito magazzino';
TT_language_it["tomtop.common.italyWarehouse"]             = 'Magazzino in Italia';
TT_language_it["tomtop.common.germanyWarehouse"]           = 'Magazzino di Germania';
TT_language_it["tomtop.common.usWarehouse"]                = 'Stati Uniti d\'America magazzino';
TT_language_it["tomtop.common.franceWarehouse"]            = 'Magazzino di Francia';
TT_language_it["tomtop.common.spainWarehouse"]             = 'Magazzino di Spagna';
TT_language_it["tomtop.common.australiaWarehouse"]         = 'Magazzino di Australia';
TT_language_it["tomtop.product.shippingFrom"]              = 'Spedizione Da';
TT_language_it["tomtop.product.warehouse"]                 = 'Magazzino';


//jpan id=7
var TT_language_jp = new Array();
TT_language_jp["tomtop.message.shoppingCartIsEmpty"]       = 'ショッピングカートは空いています！';
TT_language_jp["tomtop.common.continueShopping"]           = 'ショッピングを続けます';
TT_language_jp["tomtop.message.cannotBeEmpty"]              = '空にすることができません！';
TT_language_jp["tomtop.common.tip"]                        = 'チップ';
TT_language_jp["tomtop.message.enterYourEmail"]            = 'メールアドレスを入力してください。';
TT_language_jp["tomtop.message.wrongEmail"]                = '間違った電子メールの形式を入力しまいました！';
TT_language_jp["tomtop.product.ok"]                        = 'Ok';//ok
TT_language_jp["tomtop.product.cancel"]                    = 'キャンセル';//ok
TT_language_jp["tomtop.product.name"]                      = '名';//ok
TT_language_jp["tomtop.product.mobilePhone"]               = '携帯電話';//ok
TT_language_jp["tomtop.product.emailAddress"]              = 'メールアドレス';//ok
TT_language_jp["tomtop.product.yourTargetPrice"]           = 'あなたの予定価格';//ok
TT_language_jp["tomtop.product.orderQuantity"]             = '注文数量';//ok
TT_language_jp["tomtop.product.countryState"]              = '国/州';//ok
TT_language_jp["tomtop.product.companyName"]               = '会社名';//ok
TT_language_jp["tomtop.product.writeAnInquiry"]            = 'お問い合わせを書きます';//ok
TT_language_jp["tomtop.product.pleaseLetUsKnow"]           = '我々があなたの特定のニーズであなたを援助することができるように、あなたの質問についてできる限り私たちに知らせてください。可能な場合は、我々は常に助けて満足です。';//ok
TT_language_jp["tomtop.product.item"]                      = 'アイテム';//ok
TT_language_jp["tomtop.common.itemAddedToCart"]           = 'アイテムがカートに追加されました';
TT_language_jp["tomtop.common.totalItemInYourCart"]        = 'カート内の合計アイテム';
TT_language_jp["tomtop.common.viewCart"]                   = 'カートを見ます';
TT_language_jp["tomtop.product.addToCart"]                 = 'カートに入れます';//ok
TT_language_jp["tomtop.common.viewMore"]                   = 'View More';
TT_language_jp["tomtop.message.enterYourPassword"]          = 'パスワードを入力してください。';
TT_language_jp["tomtop.message.usernameOrPassword"]         = '不正なユーザ名またはパスワードを入力しまいました。';
TT_language_jp["tomtop.common.signIn"]                     = 'サインイン';
TT_language_jp["tomtop.common.signInWithTomTopAccount"]    = 'TOMTOPアカウントでログイン';//ok
TT_language_jp["tomtop.common.enterYourEmail"]             = 'メールアドレスを入力してください';//ok
TT_language_jp["tomtop.common.enterYourPassword"]          = 'パスワードを入力してください';//ok
TT_language_jp["tomtop.common.forgotPassword"]             = 'パスワードをお忘れですか？';//ok
TT_language_jp["tomtop.common.signInWithAnExistingAccount"]= '既存のアカウントでログイン';//ok
TT_language_jp["tomtop.common.joinToday"]                  = '本日に入会！';//ok
TT_language_jp["tomtop.common.membersOnlyService"]         = '会員限定サービス';//ok
TT_language_jp["tomtop.common.membersOnlyService1"]        = '1.報奨ポイント';//ok
TT_language_jp["tomtop.common.membersOnlyService2"]        = '2.優先カスタマーサービス';//ok
TT_language_jp["tomtop.common.membersOnlyService3"]        = '3.おすすめ';//ok
TT_language_jp["tomtop.common.membersOnlyService4"]        = '4.パーマネントショッピングカート';//ok
TT_language_jp["tomtop.common.membersOnlyService5"]        = '5.注文履歴';//ok
TT_language_jp["tomtop.common.error"]                      = 'エラー';
TT_language_jp["tomtop.common.successfully"]               = 'できました';
TT_language_jp["tomtop.common.viewCartCheckOut"]           = 'カートを見ます';//ok
TT_language_jp["tomtop.common.inStock"]                    = '在庫';
TT_language_jp["tomtop.common.outStock"]                   = '在庫切れ';
TT_language_jp["tomtop.product.regularPrice"]              = '定価';
TT_language_jp["tomtop.product.saleEndsIn"]                = '売却が　で終了します';

TT_language_jp["tomtop.common.chinaWarehouse"]             = '中国倉庫';
TT_language_jp["tomtop.common.ukWarehouse"]                = 'イギリス倉庫';
TT_language_jp["tomtop.common.italyWarehouse"]             = 'イタリアの倉庫';
TT_language_jp["tomtop.common.germanyWarehouse"]           = 'ドイツ倉庫';
TT_language_jp["tomtop.common.usWarehouse"]                = 'アメリカ合衆国倉庫';
TT_language_jp["tomtop.common.franceWarehouse"]            = 'フランスの倉庫';
TT_language_jp["tomtop.common.spainWarehouse"]             = 'スペイン倉庫';
TT_language_jp["tomtop.common.australiaWarehouse"]         = 'オーストラリア倉庫';
TT_language_jp["tomtop.product.shippingFrom"]              = 'から発送';
TT_language_jp["tomtop.product.warehouse"]                 = '倉庫';


